services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: podcast_organizer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/podcast_organizer
    depends_on:
      - db

volumes:
  pgdata:
